
#ifndef HELLOLIBRARYDLL_EXPORT_H
#define HELLOLIBRARYDLL_EXPORT_H

#ifdef HELLOLIBRARYDLL_STATIC_DEFINE
#  define HELLOLIBRARYDLL_EXPORT
#  define HELLOLIBRARYDLL_NO_EXPORT
#else
#  ifndef HELLOLIBRARYDLL_EXPORT
#    ifdef HelloLibraryDll_EXPORTS
        /* We are building this library */
#      define HELLOLIBRARYDLL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define HELLOLIBRARYDLL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef HELLOLIBRARYDLL_NO_EXPORT
#    define HELLOLIBRARYDLL_NO_EXPORT 
#  endif
#endif

#ifndef HELLOLIBRARYDLL_DEPRECATED
#  define HELLOLIBRARYDLL_DEPRECATED __declspec(deprecated)
#endif

#ifndef HELLOLIBRARYDLL_DEPRECATED_EXPORT
#  define HELLOLIBRARYDLL_DEPRECATED_EXPORT HELLOLIBRARYDLL_EXPORT HELLOLIBRARYDLL_DEPRECATED
#endif

#ifndef HELLOLIBRARYDLL_DEPRECATED_NO_EXPORT
#  define HELLOLIBRARYDLL_DEPRECATED_NO_EXPORT HELLOLIBRARYDLL_NO_EXPORT HELLOLIBRARYDLL_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef HELLOLIBRARYDLL_NO_DEPRECATED
#    define HELLOLIBRARYDLL_NO_DEPRECATED
#  endif
#endif

#endif /* HELLOLIBRARYDLL_EXPORT_H */
